version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: $AWS_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: $AWS_SECRET_ACCESS_KEY
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.18.0
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/mlflow/mlruns
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
    command: bash -c "pip install boto3 && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://$BUCKET/ --artifacts-destination s3://$BUCKET/ --host 0.0.0.0"

volumes:
  minio_data:
    driver: local
  mlruns:
    driver: local
